TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a
TARGET_CPU_ABI := armeabi-v7a

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_VENDORIMAGE_PARTITION_SIZE := 671088640

BOARD_USERDEBUG_PROPERTIES += \
ro.secure=0 \
ro.debuggable=1 \
persist.sys.usb.config=adb
